# Generated by Django 5.0 on 2023-12-12 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdmCustomer",
            fields=[
                ("customer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("street", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=20)),
                ("zipcode", models.CharField(max_length=5)),
                ("email", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("driver_license_num", models.CharField(max_length=30)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("C", "Corporate"), ("I", "Individual")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdmDiscount",
            fields=[
                (
                    "coupon_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("coupon_code", models.CharField(max_length=20)),
                ("disc_description", models.CharField(max_length=20)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[("C", "Corporate"), ("I", "Individual")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdmInvoice",
            fields=[
                ("invoice_id", models.IntegerField(primary_key=True, serialize=False)),
                ("invoice_date", models.DateField()),
                ("invoice_amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("payment_status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="IdmOffice",
            fields=[
                ("location_id", models.IntegerField(primary_key=True, serialize=False)),
                ("street_name", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("building_number", models.CharField(max_length=30)),
                ("zipcode", models.CharField(max_length=5)),
                ("phone_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="IdmCorporate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField()),
                ("registration_num", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=30)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idmcustomer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="idmcustomer",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.idmdiscount"
            ),
        ),
        migrations.CreateModel(
            name="IdmCorpCoup",
            fields=[
                (
                    "coupon_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("corp_coupon_id", models.IntegerField()),
                ("aff_company_name", models.CharField(max_length=30)),
                ("discount_percentage", models.IntegerField()),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idmdiscount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdmIndCoup",
            fields=[
                (
                    "coupon_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("indv_coupon_id", models.IntegerField()),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("discount_percentage", models.IntegerField()),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idmdiscount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdmIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("individual_id", models.IntegerField()),
                ("insurance_company_name", models.CharField(max_length=20)),
                ("insurance_policy_num", models.CharField(max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idmcustomer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdmPayment",
            fields=[
                ("payment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("payment_method", models.CharField(max_length=20)),
                ("payment_date", models.DateField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idminvoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdmCard",
            fields=[
                (
                    "card_number",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("card_type", models.CharField(max_length=30)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idmpayment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdmRentalAgr",
            fields=[
                ("rental_id", models.IntegerField(primary_key=True, serialize=False)),
                ("pickup_date", models.DateField()),
                ("dropoff_date", models.DateField()),
                ("start_odometer", models.CharField(max_length=10)),
                ("end_odometer", models.CharField(max_length=10)),
                ("daily_odometer_limit", models.CharField(max_length=10)),
                ("unlimited_mileage", models.CharField(max_length=1)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idmdiscount",
                    ),
                ),
                (
                    "dropoff_loc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropoff_location",
                        to="myapp.idmoffice",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idminvoice",
                    ),
                ),
                (
                    "pickup_loc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_location",
                        to="myapp.idmoffice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="idmcustomer",
            name="rental",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.idmrentalagr"
            ),
        ),
        migrations.CreateModel(
            name="IdmClass",
            fields=[
                ("class_id", models.IntegerField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=20)),
                ("rate_per_day", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "over_mileage_fee",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idmoffice",
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.idmrentalagr",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdmVehicles",
            fields=[
                (
                    "vin",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("make", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=30)),
                ("year", models.DateField()),
                ("license_plate_number", models.CharField(max_length=30)),
                (
                    "vehicle_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.idmclass"
                    ),
                ),
            ],
        ),
    ]
